### PR TITLE
Contao 4 support and update to version 6.1.6

### PR DESCRIPTION
**Pull request by fatcrobat**
As the titel states, we updated mmenu to 6.1.6 to provide `navbars` support. If you want merge. :)

### CODE REVIEW

**Comment by fritzmg** [comment]
The newest versions of mmenu require a commercial license.

**Comment by fatcrobat** [comment]
5.6.0 was the last version under CC-BY-NC-4.0 without commercial licence. Navbar support is already supported within 5.6.0, this module currently uses 4.7.5 from 3 years ago.

As the js plugin was updated, why not update this module as well and let the user decide to buy a licence depending on their usage?

**Comment by fritzmg** [comment]
I only know the reason why @dklemmt did not update the plugin was because of the licensing. I am not sure about the legal implications of providing a Contao extension that bundles a commercial plugin.

**Comment by fatcrobat** [comment]
CC BY-NC 4.0 licence says:

> You are free to:
> 
> Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material

> Under the following terms:
> 
> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> 
> NonCommercial — You may not use the material for commercial purposes.
> No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

If you add credits to the original author and add a note like the plugin itself:

> Licence
> 
> The jQuery.mmenu plugin is licensed under the CC-BY-NC-4.0 license.
> You can purchase a license if you want to use it in a commercial website.

you should be fine. This module is free of any charge and for commercial purposes the user have to buy a licence from the author.

**Comment by fritzmg** [comment]
> The jQuery.mmenu plugin is licensed under the Creative Commons Attribution-NonCommercial 4.0 International license. You can purchase a license if you want to use it in a commercial website.

I am guessing a majority of websites are commercial, are they not? Or what constitutes a commercial website?

**Comment by fritzmg** [comment]
Maybe @FrDH can clear this up directly ;)

**Comment by fatcrobat** [comment]
This module itself does not make any profit from the original plugin. It simply spreads the plugin to contao instances. But you are right, maybe the author will clear it up. :)

**Comment by FrDH** [comment]
Hi guys,

The license applies to "commercial end products".
There probably are some legal gray areas on what should be considered "commercial" or "end product". But in short, a commercial end product would be anything that'll gain the owner commercial benefit, either directly via profits or indirectly via increasing brand awareness.

I'd say the Contao module itself is not a commercial end product (it is free to use and the author does not gain commercial benefit from it), but most websites it is used on probably are.
Like @fatcrobat said:
> This module is free of any charge and for commercial purposes the user have to buy a licence from the author.

Hope this helps :)

**Comment by fatcrobat** [comment]
@FrDH Thanks for your clarification. :) @fritzmg If i add a notice to the readme, like at https://github.com/FrDH/jQuery.mmenu

> Licence
> 
> The jQuery.mmenu plugin is licensed under the CC-BY-NC-4.0 license.
> You can purchase a license if you want to use it in a commercial website.

would you merge the pr?

**Comment by fritzmg** [comment]
Personally I would have no objections ;).

However, I think many users simply will not know about this limitation and thus unknowingly illegally use this extension on their sites.

**Comment by fatcrobat** [comment]
I understand your concerns. But what about a 2.0 version with a big hint notice, with the licence notice to the original author?

**Comment by fritzmg** [comment]
@dklemmt what do you think?

**Comment by fatcrobat** [comment]
@fritzmg Looks like dklemmt is lost, any ETA on that?

**Comment by fritzmg** [comment]
Should we put the hint only here in the repository or also in the back end somewhere?

**Comment by dklemmt** [comment]
hey sorry hadn't seen the latest comments due to holiday absence at this time.

I would prefer a version 2.0 with a big hint. So anyone can install the latest in 1.x to use in any circumstances and to use version 2.x with the responsibility in his hands for getting a license if necessary.

**Comment by fatcrobat** [comment]
@fritzmg @dklemmt would you than merge this PR into a 2.x branch and create an initial tag please?

**Comment by fritzmg** [comment]
@fatcrobat sorry for the long delay

I'll create a new branch for the current state of the master branch and I'd then merge it into the master branch. However, I have two requests:

* Can you update to mmenu 6.1.8?
* Could you provide an update to the README.md as well, explaining the license situation?

**Comment by pagestyles** [comment]
If you look at the Download page: http://mmenu.frebsite.nl/download.html

There is a Point:

> Paid plugins, themes and templates
> 
> By purchasing ONE "Multiple websites license", you are allowed to include the jQuery.mmenu plugin in ONE product (for example a plugin, theme or template) for sale. Customers and users of your product do not need to purchase their own license.

We have no problem to deliver you this license @dklemmt to keep this great plugin alive and up to date

**Comment by fatcrobat** [comment]
@fritzmg If @pagestyles would be that generous to donate a "Multiple websites license" no explanation about the licence situation will be required?!

**Comment by fritzmg** [comment]
I have merged this into master now and created a new branch for the old `1.x` version. I'll make a few adjustments and then release it as `2.0.0`.

**Comment by fritzmg** [comment]
Hm, I actually only just tried your changes @fatcrobat - however this still does not work with Contao 4's `nav_default` template (due to the usage of `<strong>`).

See also #15 and #20.

**Comment by fritzmg** [comment]
See https://github.com/dklemmt/contao_dk_mmenu/releases/tag/2.0.0

**Comment by fatcrobat** [comment]
Still have issues with the merge?

**Comment by fritzmg** [comment]
No, the PR was merged, updated and released ;)

**Comment by fatcrobat** [comment]
Cheers! Thanks a lot.

**Comment by fritzmg** [comment]
> So, if i'm getting this right, it's just 75$ once to use it in the plugin. We have no problem to "donate" you this license @dklemmt to keep this great plugin alive and up to date.

I think that only applies to commercial plugins?

**Comment by fatcrobat** [comment]
I think you are right. This plugin is non commercial and for non profit personal usage the mmenu licence is free as well. If you fork this module and make it private with custom adjustments for your customers, than you can use this 75$ licence for all you customers. This module is potentially usable by all people on this planet for free. So @FrDh wont earn no more money with his plugin because everybody uses this contao module instead.😂

**Comment by fritzmg** [comment]
> So @FrDH wont earn no more money with his plugin because everybody uses this contao module instead.😂

No, because the commercial license would still apply to the commercial product it is used in. i.e. a commercial website.

**Comment by fatcrobat** [comment]
I know, my quote was just an exaggerated acceptance.😉

**Pull request merged**
