### PR TITLE
unlock for Contao 4

### PR DESCRIPTION
**Pull request by fritzmg**
As far as I have tested it, this extension works fine in Contao 4.

### CODE REVIEW

**Comment by fritzmg** [comment]
There is one issue though: Contao 4 uses `<strong>` instead of `<span>` for the active element now. But mmenu requires `<span>`.

**Comment by dklemmt** [comment]
oh ok I merged the pull request into master but won't do any Release yet due to this issue. I don't work much with Contao lately and don't know Contao 4 at all. If you like I can add you as a collaborator to the repository :)

**Comment by fritzmg** [comment]
Hm ok :). I won't have much time for it either, but it couldn't hurt.

**Comment by Jaaaan** [comment]
Maybe #15 ??

**Pull request merged**
